# Generated by Django 6.0 on 2026-01-26 15:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('isactive', models.BooleanField(default=True)),
                ('stripe_id', models.CharField(blank=True, max_length=120, null=True)),
                ('groups', models.ManyToManyField(to='auth.group')),
                ('permissions', models.ManyToManyField(limit_choices_to={'codename__in': ['basic', 'Pro', 'advanced', 'Enterprise'], 'content_type__app_label': 'subscriptions'}, to='auth.permission')),
            ],
            options={
                'permissions': [('basic', 'Basic Perm'), ('Pro', 'Pro Perm'), ('advanced', 'Advanced Perm'), ('Enterprise', 'Enterprise Perm')],
            },
        ),
        migrations.CreateModel(
            name='MyUserSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isactive', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('sub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SUBS.subscription')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pricing_interval', models.CharField(choices=[('month', 'Month'), ('year', 'Year')], default='month', max_length=120)),
                ('stripe_id', models.CharField(blank=True, max_length=120, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=19.99, max_digits=10)),
                ('subscription', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='SUBS.subscription')),
            ],
        ),
    ]
