# Generated by Django 6.0 on 2026-01-26 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SUBS', '0005_subscriptionprice_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionprice',
            name='order',
            field=models.IntegerField(default=-1),
        ),
    ]
