# Generated by Django 6.0 on 2026-01-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SUBS', '0006_subscriptionprice_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='features',
            field=models.TextField(blank=True, help_text='Features fot the individual subscription plans', null=True),
        ),
    ]
