# Generated by Django 6.0 on 2026-02-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SUBS', '0007_subscription_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='features',
            field=models.TextField(blank=True, help_text='Features for the individual subscription plans', null=True),
        ),
    ]
