# Generated by Django 6.0 on 2026-02-09 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SUBS', '0008_alter_subscription_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusersubscription',
            name='stripe_id',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
