# Generated by Django 6.0 on 2026-02-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SUBS', '0009_myusersubscription_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusersubscription',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='myusersubscription',
            name='current_period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myusersubscription',
            name='current_period_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myusersubscription',
            name='original_period_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myusersubscription',
            name='user_cancelled',
            field=models.BooleanField(default=False),
        ),
    ]
