# Generated by Django 6.0 on 2026-02-12 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SUBS', '0010_myusersubscription_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusersubscription',
            name='status',
            field=models.CharField(blank=True, choices=[('active', 'Active'), ('trialing', 'Trialing'), ('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete Expired'), ('past_due', 'Past Due'), ('cancelled', 'Cancelled'), ('unpaid', 'Unpaid'), ('unused', 'Unused')], max_length=20, null=True),
        ),
    ]
