# Generated by Django 6.0 on 2026-02-13 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SUBS', '0011_myusersubscription_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myusersubscription',
            name='isactive',
        ),
    ]
