# Generated by Django 6.0 on 2026-02-16 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SUBS', '0012_remove_myusersubscription_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusersubscription',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
    ]
