# Generated by Django 6.0 on 2026-02-20 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SUBS', '0013_myusersubscription_cancel_at_period_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusersubscription',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
