# Generated by Django 6.0 on 2026-02-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SUBS', '0014_alter_myusersubscription_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusersubscription',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
