name: 1-Hello-Darkness Github actions

on: #workflow triggering 
  push:
   branch:
    - main

jobs:
 Baby:
  steps:
   - name: Baby Baby would you go ahead and just cry!,cry...
     run: echo "Hello Baby NO"