name: 2-Test Django Basics


on:
   workflow_dispatch:
   push:
    branch:
     - main


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
     - name: Checkout code
       uses:  actions/checkout@v6
       - uses: actions/setup-python@v6
     - name: install python (3.12)
       with:
        
       python-version: '3.12' 
     - name:  install requirements.txt
       run:
          pip install -r requirements.txt
     - name: My Django Tests
       working-directory: ./src
       run:
          python manage.py test

 
       

  







