name: 4Test Django Database url

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
         #  DJANGO_SECRET_KEY: insecure ass bitch
           DJANGO_DEBUG: False
           DATABASE_URL: ${{secrets.NEON_DATABASE_URL}}
        run: python manage.py test
    #LLOW the steps to have access to the environment variables
    #place the environment vars before steps   
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
          #auto genertate django secret key
      - name: Setup django secret key
        run: |
           my_gen_key=$(openssl rand -base64 32)
           echo "DJANGO_SECRET_KEY=$my_gen_key" >> $GITHUB_ENV
      - name: Show Database url
        run: |
            echo ${{env.DATABASE_URL}}
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run Django tests
        working-directory: ./src
        run: python manage.py test